# Generated by Django 4.1.7 on 2023-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabrasIngresadas', models.CharField(max_length=6, verbose_name='Palabras ingresadas')),
                ('estadoDelaPalabra', models.CharField(max_length=200, verbose_name='Estado de la palabra')),
            ],
        ),
    ]
